# Generated by Django 5.2.13 on 2026-04-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="normalizedlog",
            new_name="logs_normal_source__f4b289_idx",
            old_name="logs_norm_source_time_idx",
        ),
        migrations.RenameIndex(
            model_name="normalizedlog",
            new_name="logs_normal_user_em_3160fc_idx",
            old_name="logs_norm_user_time_idx",
        ),
        migrations.RenameIndex(
            model_name="normalizedlog",
            new_name="logs_normal_action_ec0544_idx",
            old_name="logs_norm_action_outcome_idx",
        ),
        migrations.RenameIndex(
            model_name="normalizedlog",
            new_name="logs_normal_geo_cou_5c3434_idx",
            old_name="logs_norm_country_idx",
        ),
        migrations.RenameIndex(
            model_name="normalizedlog",
            new_name="logs_normal_severit_86aaa2_idx",
            old_name="logs_norm_severity_time_idx",
        ),
        migrations.RenameIndex(
            model_name="rawlog",
            new_name="logs_rawlog_source__4e8583_idx",
            old_name="logs_raw_source_received_idx",
        ),
        migrations.RenameIndex(
            model_name="rawlog",
            new_name="logs_rawlog_is_norm_b83020_idx",
            old_name="logs_raw_normalized_idx",
        ),
        migrations.RenameIndex(
            model_name="rawlog",
            new_name="logs_rawlog_connect_3845ef_idx",
            old_name="logs_raw_connector_idx",
        ),
    ]
