# Generated by Django 5.2.13 on 2026-07-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_rename_logs_norm_source_time_idx_logs_normal_source__f4b289_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawlog',
            name='source_type',
            field=models.CharField(choices=[('microsoft365', 'Microsoft 365'), ('google_workspace', 'Google Workspace'), ('wazuh', 'Wazuh'), ('syslog', 'Syslog'), ('manual', 'Manuel'), ('logplus', 'Log+ (plateforme)')], max_length=50, verbose_name='Type de source'),
        ),
    ]
