# Generated by Django 5.2.13 on 2026-07-14 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0003_collectionjob_organization_and_more'),
        ('logs', '0003_alter_rawlog_source_type'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedlog',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="Dénormalisé depuis raw_log.organization pour l'isolation multi-tenant.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalized_logs', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='rawlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_logs', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddIndex(
            model_name='normalizedlog',
            index=models.Index(fields=['organization', 'event_time'], name='logs_normal_organiz_fc4fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='rawlog',
            index=models.Index(fields=['organization', 'received_at'], name='logs_rawlog_organiz_21189d_idx'),
        ),
    ]
