# Generated by Django 5.2.13 on 2026-07-14 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_normalizedlog_organization_rawlog_organization_and_more'),
        ('organizations', '0002_backfill_legacy_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedlog',
            name='organization',
            field=models.ForeignKey(help_text="Dénormalisé depuis raw_log.organization pour l'isolation multi-tenant.", on_delete=django.db.models.deletion.CASCADE, related_name='normalized_logs', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='rawlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_logs', to='organizations.organization', verbose_name='Organisation'),
        ),
    ]
