# Generated by Django 5.2.13 on 2026-07-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_normalizedlog_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawlog',
            name='source_type',
            field=models.CharField(choices=[('microsoft365', 'Microsoft 365'), ('google_workspace', 'Google Workspace'), ('wazuh', 'Wazuh'), ('syslog', 'Syslog'), ('agent', 'Agent Log+ (HTTP authentifié)'), ('manual', 'Manuel'), ('logplus', 'Log+ (plateforme)')], max_length=50, verbose_name='Type de source'),
        ),
    ]
