# Generated by Django 5.2.13 on 2026-07-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_alter_rawlog_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawlog',
            name='source_type',
            field=models.CharField(choices=[('microsoft365', 'Microsoft 365'), ('google_workspace', 'Google Workspace'), ('wazuh', 'Wazuh'), ('syslog', 'Syslog'), ('agent', 'Agent Argus (HTTP authentifié)'), ('manual', 'Manuel'), ('argus', 'Argus (plateforme)')], max_length=50, verbose_name='Type de source'),
        ),
    ]
