# Generated by Django 5.2.13 on 2026-07-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_alter_rawlog_source_type'),
        ('organizations', '0003_organization_is_demo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='normalizedlog',
            index=models.Index(fields=['source_ip', 'event_time'], name='logs_normal_source__ac03b0_idx'),
        ),
    ]
