# Generated by Django 5.2.13 on 2026-04-18 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
        ("correlation", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="alert",
            new_name="alerts_aler_severit_12d0e1_idx",
            old_name="alerts_severity_status_idx",
        ),
        migrations.RenameIndex(
            model_name="alert",
            new_name="alerts_aler_status_bbfb4b_idx",
            old_name="alerts_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="alert",
            new_name="alerts_aler_assigne_28b530_idx",
            old_name="alerts_assigned_status_idx",
        ),
        migrations.AddField(
            model_name="alert",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="correlation.correlationrule",
                verbose_name="Règle déclencheuse",
            ),
        ),
    ]
