# Generated by Django 5.2.13 on 2026-07-14 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_rename_alerts_severity_status_idx_alerts_aler_severit_12d0e1_idx_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='organizations.organization', verbose_name='Organisation'),
        ),
    ]
