# Generated by Django 5.2.13 on 2026-07-14 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_organization'),
        ('organizations', '0002_backfill_legacy_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='organizations.organization', verbose_name='Organisation'),
        ),
    ]
