# Generated by Django 5.2.13 on 2026-07-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_alert_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='ai_recommended_actions',
            field=models.JSONField(blank=True, default=list, verbose_name='Actions recommandées (IA)'),
        ),
        migrations.AddField(
            model_name='alert',
            name='ai_summary',
            field=models.TextField(blank=True, verbose_name='Résumé généré par IA'),
        ),
        migrations.AddField(
            model_name='alert',
            name='ai_summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
