# Generated by Django 5.2.13 on 2026-07-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='geo_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='geo_country',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Pays (ISO 3166-1 alpha-2)'),
        ),
    ]
