# Generated by Django 5.2.13 on 2026-07-14 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0003_audittrail_geo_city_audittrail_geo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Null pour les évènements système plateforme (visibles du super-admin uniquement).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trails', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Null uniquement pour le staff plateforme (is_superuser).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organizations.organization', verbose_name='Organisation'),
        ),
    ]
