# Generated by Django 5.2.13 on 2026-07-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_audittrail_organization_user_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="critical_alert_emails",
            field=models.BooleanField(
                default=True,
                help_text="Notification email immédiate pour les alertes critiques.",
                verbose_name="Alertes critiques par email",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Recevoir les notifications de sécurité par email.",
                verbose_name="Notifications par email",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="weekly_report_email",
            field=models.BooleanField(
                default=False,
                help_text="Recevoir un résumé hebdomadaire de l'activité par email.",
                verbose_name="Rapport hebdomadaire par email",
            ),
        ),
    ]
