# Generated by Django 5.2.13 on 2026-07-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_critical_alert_emails_user_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo_spectator',
            field=models.BooleanField(default=False, help_text='Compte utilisé par le lien magique / QR code public. Forcé en lecture seule au niveau middleware (utils.demo_readonly), indépendamment du rôle et des permissions déclarées par chaque vue — voir MIDDLEWARE dans config.settings.base.', verbose_name='Spectateur démo'),
        ),
    ]
