# Generated by Django 5.2.13 on 2026-04-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threat_intel", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="threatindicator",
            new_name="threat_inte_indicat_8731c0_idx",
            old_name="threat_ind_type_malicious_idx",
        ),
        migrations.RenameIndex(
            model_name="threatindicator",
            new_name="threat_inte_reputat_4ab8c7_idx",
            old_name="threat_ind_score_idx",
        ),
        migrations.AlterField(
            model_name="threatindicator",
            name="confidence",
            field=models.FloatField(default=0.0, help_text="0.0 à 1.0"),
        ),
        migrations.AlterField(
            model_name="threatindicator",
            name="reputation_score",
            field=models.FloatField(
                default=0.0, help_text="0.0 (safe) à 100.0 (malicious)"
            ),
        ),
    ]
