# Generated by Django 5.2.13 on 2026-07-14 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('threat_intel', '0002_rename_threat_ind_type_malicious_idx_threat_inte_indicat_8731c0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichedlog',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="Dénormalisé depuis log.organization pour l'isolation multi-tenant.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enriched_logs', to='organizations.organization', verbose_name='Organisation'),
        ),
    ]
