# Generated by Django 5.2.13 on 2026-07-14 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_backfill_legacy_organization'),
        ('threat_intel', '0003_enrichedlog_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichedlog',
            name='organization',
            field=models.ForeignKey(help_text="Dénormalisé depuis log.organization pour l'isolation multi-tenant.", on_delete=django.db.models.deletion.CASCADE, related_name='enriched_logs', to='organizations.organization', verbose_name='Organisation'),
        ),
    ]
