# Generated by Django 5.2.13 on 2026-07-22 09:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_is_demo'),
        ('threat_intel', '0004_alter_enrichedlog_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatindicator',
            name='source',
            field=models.CharField(choices=[('abuseipdb', 'AbuseIPDB'), ('virustotal', 'VirusTotal'), ('manual', 'Manuel'), ('otx', 'AlienVault OTX'), ('urlhaus', 'abuse.ch URLhaus (communautaire)'), ('feodotracker', 'abuse.ch Feodo Tracker (communautaire)'), ('federation', 'Réseau collaboratif Argus (instances fédérées)')], default='abuseipdb', max_length=30),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'actif")),
                ('asset_type', models.CharField(choices=[('server', 'Serveur'), ('workstation', 'Poste de travail'), ('network_device', 'Équipement réseau'), ('application', 'Application'), ('cloud_service', 'Service cloud'), ('other', 'Autre')], default='server', max_length=30)),
                ('vendor', models.CharField(blank=True, max_length=255, verbose_name='Éditeur/Fabricant')),
                ('product', models.CharField(blank=True, max_length=255, verbose_name='Produit')),
                ('version', models.CharField(blank=True, max_length=100)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('criticality', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Saisie manuelle'), ('auto_detected', 'Détection automatique')], default='manual', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='organizations.organization')),
            ],
            options={
                'ordering': ['-criticality', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CVERecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cve_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Identifiant CVE')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cvss_score', models.FloatField(blank=True, null=True, verbose_name='Score CVSS')),
                ('severity', models.CharField(blank=True, choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], db_index=True, max_length=20)),
                ('vendor_project', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Éditeur')),
                ('product', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Produit')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('is_kev', models.BooleanField(db_index=True, default=False, verbose_name='Exploitée activement (CISA KEV)')),
                ('kev_date_added', models.DateTimeField(blank=True, null=True)),
                ('kev_due_date', models.DateTimeField(blank=True, null=True)),
                ('kev_ransomware_use', models.BooleanField(default=False, verbose_name='Utilisée par des ransomwares connus')),
                ('kev_required_action', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_kev', '-cvss_score', '-published_date'],
                'indexes': [models.Index(fields=['is_kev', 'severity'], name='threat_inte_is_kev_ce8fde_idx'), models.Index(fields=['vendor_project', 'product'], name='threat_inte_vendor__36c4d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetVulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('acknowledged', 'Prise en compte'), ('mitigated', 'Corrigée'), ('false_positive', 'Faux positif')], db_index=True, default='open', max_length=20)),
                ('matched_reason', models.CharField(blank=True, max_length=255)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='threat_intel.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_vulnerabilities', to='organizations.organization')),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_assets', to='threat_intel.cverecord')),
            ],
            options={
                'ordering': ['-matched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'vendor', 'product'], name='threat_inte_organiz_4cfcaf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetvulnerability',
            unique_together={('asset', 'cve')},
        ),
    ]
