# Generated by Django 5.2.13 on 2026-04-27 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_linked_accounts"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="linkedaccount",
            new_name="authenticat_user_id_90bafd_idx",
            old_name="auth_linked_user_provid_idx",
        ),
        migrations.RenameIndex(
            model_name="linkedaccount",
            new_name="authenticat_status_52de5a_idx",
            old_name="auth_linked_status_polled_idx",
        ),
        migrations.RenameIndex(
            model_name="loginconfirmation",
            new_name="authenticat_user_id_49ee20_idx",
            old_name="auth_conf_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="loginconfirmation",
            new_name="authenticat_status_420798_idx",
            old_name="auth_conf_status_exp_idx",
        ),
        migrations.RenameIndex(
            model_name="providerloginevent",
            new_name="authenticat_linked__36c04c_idx",
            old_name="auth_evt_acc_time_idx",
        ),
        migrations.RenameIndex(
            model_name="providerloginevent",
            new_name="authenticat_event_t_0f398d_idx",
            old_name="auth_evt_type_time_idx",
        ),
        migrations.RenameIndex(
            model_name="securitynotification",
            new_name="authenticat_user_id_559fc0_idx",
            old_name="auth_notif_user_read_idx",
        ),
        migrations.RenameIndex(
            model_name="securitynotification",
            new_name="authenticat_kind_4a6cf4_idx",
            old_name="auth_notif_kind_time_idx",
        ),
    ]
