# Generated by Django 5.2.13 on 2026-04-28 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_auth_linked_user_provid_idx_authenticat_user_id_90bafd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLinkVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=20)),
                ('provider_email', models.EmailField(max_length=254)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('provider_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=512)),
                ('oauth_data', models.JSONField(default=dict)),
                ('pin', models.CharField(max_length=4)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vérification de liaison',
                'verbose_name_plural': 'Vérifications de liaison',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used', 'expires_at'], name='authenticat_user_id_c033db_idx')],
            },
        ),
    ]
