# Generated by Django 5.2.13 on 2026-07-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_account_link_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitynotification',
            name='kind',
            field=models.CharField(choices=[('login_new_device', 'Nouvelle connexion (device inconnu)'), ('login_new_location', 'Nouvelle connexion (lieu inconnu)'), ('impossible_travel', 'Déplacement impossible'), ('brute_force', 'Tentative de brute-force'), ('account_locked', 'Compte verrouillé'), ('account_unlinked', 'Compte délié'), ('provider_error', 'Erreur provider'), ('info', 'Information')], max_length=40),
        ),
    ]
