# Generated by Django 5.2.13 on 2026-04-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playbook",
            name="actions",
            field=models.JSONField(
                default=list,
                help_text="Liste d'actions: [{type: 'send_email', params: {...}}, ...]",
            ),
        ),
        migrations.AlterField(
            model_name="playbook",
            name="trigger_conditions",
            field=models.JSONField(
                default=dict,
                help_text="Ex: {severity: ['critical','high'], rule_ids: [...]}",
            ),
        ),
    ]
