# Generated by Django 5.2.13 on 2026-07-14 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('soar', '0002_alter_playbook_actions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='playbookexecution',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="Dénormalisé depuis playbook.organization pour l'isolation multi-tenant.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playbook_executions', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='playbook',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_playbook_name_per_org'),
        ),
    ]
