# Generated by Django 5.2.13 on 2026-07-14 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_backfill_legacy_organization'),
        ('soar', '0003_playbook_organization_playbookexecution_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='playbookexecution',
            name='organization',
            field=models.ForeignKey(help_text="Dénormalisé depuis playbook.organization pour l'isolation multi-tenant.", on_delete=django.db.models.deletion.CASCADE, related_name='playbook_executions', to='organizations.organization', verbose_name='Organisation'),
        ),
    ]
