# Generated by Django 5.2.13 on 2026-07-22 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_is_demo'),
        ('soar', '0004_alter_playbook_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('soar_playbook', 'Playbook SOAR'), ('manual', 'Blocage manuel'), ('threat_intel', 'Threat Intelligence')], default='soar_playbook', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_ips', to='organizations.organization', verbose_name='Organisation')),
                ('playbook_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to='soar.playbookexecution')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'is_active'], name='soar_blocke_ip_addr_2bcbac_idx')],
            },
        ),
    ]
