# Generated by Django 5.2.13 on 2026-04-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="collectionjob",
            new_name="collectors__connect_77f27d_idx",
            old_name="collectors_job_connector_status_idx",
        ),
        migrations.RenameIndex(
            model_name="collectionjob",
            new_name="collectors__started_003ba0_idx",
            old_name="collectors_job_started_at_idx",
        ),
    ]
