# Generated by Django 5.2.13 on 2026-07-14 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0002_rename_collectors_job_connector_status_idx_collectors__connect_77f27d_idx_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionjob',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="Dénormalisé depuis connector.organization pour l'isolation multi-tenant.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_jobs', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='connectorconfig',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='organizations.organization', verbose_name='Organisation'),
        ),
    ]
