# Generated by Django 5.2.13 on 2026-07-14 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0003_collectionjob_organization_and_more'),
        ('organizations', '0002_backfill_legacy_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionjob',
            name='organization',
            field=models.ForeignKey(help_text="Dénormalisé depuis connector.organization pour l'isolation multi-tenant.", on_delete=django.db.models.deletion.CASCADE, related_name='collection_jobs', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='connectorconfig',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='organizations.organization', verbose_name='Organisation'),
        ),
    ]
