# Generated by Django 5.2.13 on 2026-07-14 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0004_alter_collectionjob_organization_and_more'),
        ('organizations', '0002_backfill_legacy_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorconfig',
            name='allowed_source_ips',
            field=models.JSONField(blank=True, default=list, help_text="Liste d'IP/CIDR autorisées à pousser du syslog UDP vers ce connecteur. Non utilisé par l'ingestion HTTP authentifiée par token (agents).", verbose_name='Adresses IP autorisées (mode syslog UDP self-host uniquement)'),
        ),
        migrations.AlterField(
            model_name='connectorconfig',
            name='source_type',
            field=models.CharField(choices=[('microsoft365', 'Microsoft 365'), ('google_workspace', 'Google Workspace'), ('wazuh', 'Wazuh SIEM'), ('syslog', 'Syslog'), ('agent', 'Agent Log+ (HTTP authentifié)')], max_length=50, verbose_name='Type de source'),
        ),
        migrations.CreateModel(
            name='AgentEnrollmentToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex: « Serveurs web prod », « Parc Windows siège »', max_length=200, verbose_name='Nom')),
                ('token_prefix', models.CharField(db_index=True, max_length=8, verbose_name='Préfixe (lookup rapide)')),
                ('token_hash', models.CharField(max_length=64, verbose_name='Hash SHA-256 du token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier usage')),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dernière IP')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('connector', models.ForeignKey(blank=True, help_text='Créé/lié automatiquement au premier usage du token.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_tokens', to='collectors.connectorconfig', verbose_name='Connecteur associé')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_tokens', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Token d'enrôlement d'agent",
                'verbose_name_plural': "Tokens d'enrôlement d'agents",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_prefix', 'is_active'], name='collectors__token_p_80176f_idx')],
            },
        ),
    ]
