# Generated by Django 5.2.13 on 2026-07-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0005_connectorconfig_allowed_source_ips_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectorconfig',
            name='source_type',
            field=models.CharField(choices=[('microsoft365', 'Microsoft 365'), ('google_workspace', 'Google Workspace'), ('wazuh', 'Wazuh SIEM'), ('syslog', 'Syslog'), ('agent', 'Agent Argus (HTTP authentifié)')], max_length=50, verbose_name='Type de source'),
        ),
    ]
