# Generated by Django 5.2.13 on 2026-04-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hunting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="huntingquery",
            name="query_params",
            field=models.JSONField(
                default=dict,
                help_text="Filtres: {action, outcome, severity, source_type, geo_country, user_email, source_ip, date_from, date_to, extra_fields}",
            ),
        ),
    ]
