# Generated by Django 5.2.13 on 2026-07-14 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunting', '0002_alter_huntingquery_query_params'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='huntingquery',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunting_queries', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='huntingresult',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="Dénormalisé depuis query.organization pour l'isolation multi-tenant.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunting_results', to='organizations.organization', verbose_name='Organisation'),
        ),
    ]
