# Generated by Django 5.2.13 on 2026-07-15 15:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_backfill_legacy_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("soc_weekly", "Rapport hebdomadaire SOC"),
                            ("iso27001", "Conformité ISO 27001"),
                            ("gdpr", "Conformité RGPD"),
                            ("pci_dss", "Conformité PCI DSS"),
                            ("top_threats", "Top menaces détectées"),
                            ("user_activity", "Activité utilisateurs"),
                            ("custom", "Rapport personnalisé"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Libellé")),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("csv", "CSV"), ("json", "JSON")],
                        default="pdf",
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                (
                    "period_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Période (jours)"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="reports/%Y/%m/", verbose_name="Fichier"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Taille (octets)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Généré le"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to="organizations.organization",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport généré",
                "verbose_name_plural": "Rapports générés",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="reports_gen_organiz_55d83e_idx",
                    )
                ],
            },
        ),
    ]
