# Generated by Django 5.2.13 on 2026-04-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ml", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="prediction",
            new_name="ml_predicti_is_anom_b1f5a3_idx",
            old_name="ml_pred_anomaly_time_idx",
        ),
        migrations.RenameIndex(
            model_name="prediction",
            new_name="ml_predicti_anomaly_3577b7_idx",
            old_name="ml_pred_score_idx",
        ),
    ]
