# Generated by Django 5.2.13 on 2026-07-14 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_mlmodel_organization_prediction_organization'),
        ('organizations', '0002_backfill_legacy_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='organization',
            field=models.ForeignKey(help_text='Chaque organisation entraîne son propre modèle sur son propre corpus de logs.', on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to='organizations.organization', verbose_name='Organisation'),
        ),
    ]
