# Generated by Django 5.2.13 on 2026-07-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alert_ai_recommended_actions_alert_ai_summary_and_more'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='linked_alerts',
            field=models.ManyToManyField(blank=True, related_name='linked_tickets', to='alerts.alert', verbose_name='Alertes associées'),
        ),
    ]
