# Generated by Django 5.2.13 on 2026-07-14 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlation', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='correlationrule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correlation_rules', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='rulematch',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="Dénormalisé depuis rule.organization pour l'isolation multi-tenant.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_matches', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='correlationrule',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom de la règle'),
        ),
        migrations.AddConstraint(
            model_name='correlationrule',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_rule_name_per_org'),
        ),
    ]
