# Generated by Django 5.2.13 on 2026-07-14 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlation', '0002_correlationrule_organization_rulematch_organization_and_more'),
        ('organizations', '0002_backfill_legacy_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlationrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_rules', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='rulematch',
            name='organization',
            field=models.ForeignKey(help_text="Dénormalisé depuis rule.organization pour l'isolation multi-tenant.", on_delete=django.db.models.deletion.CASCADE, related_name='rule_matches', to='organizations.organization', verbose_name='Organisation'),
        ),
    ]
