# Generated by Django 5.2.13 on 2026-07-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlation', '0003_alter_correlationrule_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlationrule',
            name='compliance_controls',
            field=models.JSONField(blank=True, default=list, help_text="Ex: ['iso27001:A.5.15', 'pci_dss:REQ-10', 'nist_csf:PR.AC-1']", verbose_name='Contrôles de conformité couverts'),
        ),
    ]
