# Generated by Django 5.2.13 on 2026-07-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_backfill_legacy_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_demo',
            field=models.BooleanField(default=False, help_text="Tenant de démonstration public (lien magique / QR code) : isolé comme n'importe quel tenant, mais ses actions à effet de bord réel (emails, webhooks, blocages IP) sont simulées et ses données sont réinitialisables via `reset_demo_tenant`."),
        ),
    ]
